replicaCount: 2

namespace: entra-ns

appName: entra

feCert:
  name: fe-tls-secret
  namespace: entra-ns

image:
  name: entra
  repository: vhacr.azurecr.io
  pullPolicy: Always
  tag: latest # 4cda6932965dfa1c0f1eb764358a7baf4d472d49

nodeSelector:
  name: usernodepool

configMap:
  name: entra-config
  data:
    claims: |
      {
        "claims": [
          {
            "id": 1,
            "name": "Claim 1",
            "description": "Description 1"
          },
          {
            "id": 2,
            "name": "Claim 2",
            "description": "Description 2"
          },
          {
            "id": 3,
            "name": "Claim 3",
            "description": "Description 3"
          }
        ]
      }
