apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Values.appName }}-gateway
  namespace: {{ .Values.namespace }}
  annotations:
    alb.networking.azure.io/alb-id: "/subscriptions/df2f960a-8e92-40ec-a2b8-0a2923d3c074/resourceGroups/aks-rg/providers/Microsoft.ServiceNetworking/trafficControllers/alb-nk"
  
spec:
  gatewayClassName: azure-alb-external
  listeners:
  - name: {{ .Values.appName }}-listener
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: Same
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        group: ""
        name: {{ .Values.feCert.name }}
  addresses:
  - type: alb.networking.azure.io/alb-frontend
    value: fe-nk

