apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: http-route
  namespace: {{ .Values.namespace }}
spec:
  parentRefs:
  - name: {{ .Values.appName }}-gateway
  hostnames:
  - "staging.pocvivahealth.com"
  - "claimsworkflowtest.pocvivahealth.com"
  - "www.pocvivahealth.com"
  - "helm.pocvivahealth.com"
  rules:
  - backendRefs:
    - name: {{ .Values.appName }}-service
      port: 3000
     