apiVersion: apps/v1
kind: Deployment
# deploy to usernode pool
metadata:
  name: ag4claims-deployment
  namespce: ag4claims-ns
  labels:
    app: ag4claims
spec:

  replicas: 2
  selector:
    matchLabels:
      app: ag4claims
  template:
    metadata:
      labels:
        app: ag4claims
    spec:
      
      containers:
      - name: k
        image: vhacr.azurecr.io/ag4claims:latest
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
              memory: "256Mi"
              cpu: "1000m"
        ports:
        - containerPort: 3000
          
          