apiVersion: apps/v1
kind: Deployment
# deploy to usernode pool
metadata:
  name: entra-deployment
  namespace: entra-ns
  labels:
    app: entra
spec:

  replicas: 2
  selector:
    matchLabels:
      app: entra
  template:
    metadata:
      labels:
        app: entra
    spec:
      
      containers:
      - name: entra
        image: vhacr1.azurecr.io/entra:latest
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
              memory: "256Mi"
              cpu: "1000m"
        ports:
        - containerPort: 3000
          
          