apiVersion: apps/v1
kind: Deployment
# deploy to usernode pool
metadata:
  name: appdir-prisma-deployment
  namespace: prisma
  labels:
    app: appdir-prisma
spec:

  replicas: 2
  selector:
    matchLabels:
      app: appdir-prisma
  template:
    metadata:
      labels:
        app: appdir-prisma
    spec:
      
      containers:
      - name: appdir-prisma
        image: vhacr1.azurecr.io/appdir-prisma:latest
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
              memory: "256Mi"
              cpu: "1000m"
        ports:
        - containerPort: 3000
          
          