apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: gateway-01
  namespace: test-infra
spec:
  gatewayClassName: istio
  listeners:
  - name: listener-01
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from:
        selector:
          matchLabels:
            istio: ingressgateway

