apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: http-route
  namespace: ag4claims-ns
spec:
  parentRefs:
  - name: ag4claims-gateway
  hostnames:
  - "staging.pocvivahealth.com"
  - "claimsworkflowtest.pocvivahealth.com"
  rules:
  - backendRefs:
    - name: ag4claims-service
      port: 3000
     