apiVersion: v1
kind: Service
metadata:
  name: appdir-prisma-service
  namespace: prisma
spec:
  type: ClusterIP
  selector:
    app: appdir-prisma
  ports:
    - protocol: TCP
      name: http
      port: 3000
      targetPort: 3000