apiVersion: v1
kind: Service
metadata:
  name: ag4claims-service
  namespace: ag4claims-ns
  labels:
    app: ag4claims
spec:
  type: ClusterIP
  selector:
    app: ag4claims
  ports:
    - protocol: TCP
      name: http
      port: 3000
      targetPort: 3000