name: math print

on: workflow_dispatch

jobs:
  job_3:
    name: Display results

    permissions:
      contents: read
      actions: write
    
    runs-on: macOS-latest

    steps:

      - name: Download math result for job 2
        uses: actions/download-artifact@v4
        with:
          name: homework
      - name: Print the final result
        shell: bash
        run: |
          value=`cat math-homework.txt`
          echo The result is $value
